### ISSUE TITLE
Error occurred!

### ISSUE THREAD

**Issue by 6yaozt** [DARPA-4-AUI/OCR#1]
When I used more than one client to access the server, results can be sent to the wrong client! The code is too complicated for me to fix by myself. Hope you can fix this bug well and soon!

**Comment by AuKeeWa** [comment]
I am also encountering the same issue as described here. Any help or guidance on resolving this would be greatly appreciated.

**Comment by PilotKW** [comment]
I am also encountering the same issue as described here. Any help or guidance on resolving this would be greatly appreciated.

**Comment by Flora1003Xu** [comment]
This issue has been fixed! U can update ur code by re-clone the project or only update ur app.py file. Thx!
